### ISSUE TITLE
Codeception tests not working in PHPStorm

### ISSUE THREAD

**Issue by aprokopenko** [justcoded/yii2-starter-kit#25]
Very similar issue:
https://github.com/Codeception/Codeception/issues/4476

For some reason Session works incorrectly. It resets (clean up) each time you try to access a SESSION key through Yii session component.

Need to check standard basic/advanced templates for this issue.

**Comment by iamjonbradley** [comment]
I am having the same issue running tests when using Codeception with Phalcon

**Comment by aprokopenko** [comment]
Need to try this solution:
https://github.com/Codeception/Codeception/issues/4476#issuecomment-368946638

**Comment by aprokopenko** [comment]
Solution works, added patch as composer script in v0.9:

https://github.com/justcoded/yii2-starter/pull/30/commits/ec30967193b321e386be9092c983522e0ae8911a
