### ISSUE TITLE
Fatal error in console if .env file does not exist

### ISSUE THREAD

**Issue by Linguisto** [justcoded/yii2-starter-kit#41]
**Steps to reproduce**
1. Ensure that .env does not exist
2. Run any console script like `php yii hello`

**Expected result:** the console outputs a warning that .env file does not exist. Ideally, proposes to create one then from the `.env-example`.
**Actual result:** The fatal error "PHP Fatal error:  Uncaught Dotenv\Exception\InvalidPathException: Unable to read the environment file"

**Comment by aprokopenko** [comment]
I think it's correct behavior, that application is not running w/o required environment variables.
